version: "3.8"

services:
  music_store_db:
      container_name: music_store_db
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
        - ./db-init/01_model.sql:/docker-entrypoint-initdb.d/01_model.sql
        - ./db-init/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
      networks:
        - custom_network

  # Python Application Service
  app:
    container_name: music_store_assistant
    build: .  # Build the context from current directory
    ports:
      - "8000:8000"  # Port for your application (adjust if needed)
    depends_on:
      - music_store_db
    volumes:
      - ./:/app  # Mount your application directory
    command: chainlit run app.py --host=0.0.0.0 --port=8000
    networks:
      - custom_network

volumes:
  db:
    driver: local

networks:
  custom_network:
    name : custom_network
