version: "3.8"

services:
  db:
      container_name: db
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
        - ./db-init/db.sql:/docker-entrypoint-initdb.d/db.sql

  # Python Application Service
  app:
    container_name: music_store_assistant
    build: .  # Build the context from current directory
    ports:
      - "8000:8000"  # Port for your application (adjust if needed)
    depends_on:
      - db
    volumes:
      - ./:/app  # Mount your application directory
    command: python app.py

volumes:
  db:
    driver: local

networks:
  custom_network:
    name : custom_network
